SELECT * FROM employees
WHERE UPPER(FIRST_NAME) = 'ALEXANDER';

SELECT * FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) = 'alexander';

SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES
where department_id > 100;

SELECT UPPER(FIRST_NAME || ' ' || LAST_NAME) "NOME_COMPLETO"
FROM EMPLOYEES
where department_id > 100;

SELECT FIRST_NAME, INSTR(FIRST_NAME, 'l',1,2) FROM EMPLOYEES;

SELECT 'ALEXANDER GOBATTO-39',
INSTR('ALEXANDER GOBATTO-39', '-'),
SUBSTR('ALEXANDER GOBATTO-39', INSTR('ALEXANDER GOBATTO-39', '-')+1,2)
FROM DUAL

SELECT SUBSTR('ALEXANDER GOBATTO-39', INSTR('ALEXANDER GOBATTO-39', '-'),-INSTR('ALEXANDER GOBATTO-39', '-'))
FROM DUAL;

SELECT 'ALEXANDER GOBATTO-39',
INSTR('ALEXANDER GOBATTO-39', '-'),
SUBSTR('ALEXANDER GOBATTO-39', INSTR('ALEXANDER GOBATTO-39', '-')+1,2),
SUBSTR('ALEXANDER GOBATTO-39', 1,INSTR('ALEXANDER GOBATTO-39', '-')-1)
FROM DUAL;

SELECT TRUNC(COMMISSION_PCT, 0) FROM EMPLOYEES