/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Paciente;
import dao.PacienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amilton
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Aula10
     */
    public Formulario() {
        initComponents();
    }

    private Paciente montaPaciente() {
        Paciente pac = new Paciente();
        pac.setPaciente(txtPaciente.getText());
        pac.setNascimento(txtNascimento.getText());
        pac.setSexo(cmbSexo.getSelectedItem().toString());
        return pac;
    }

    public void carregarLista() {
        String titulos[] = {"Código", "Paciente", "Nascimento", "Sexo"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        ArrayList<Paciente> lista = new PacienteDAO().listaPacientes();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new Object[]{
                lista.get(i).getCodigo(),
                lista.get(i).getPaciente(),
                lista.get(i).getNascimento(),
                lista.get(i).getSexo()
            });
        }
        tblPacientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        txtPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Médica UNICSUL");
        getContentPane().setLayout(null);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Paciente", "Nascimento", "Sexo"
            }
        ));
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPacientesMouseReleased(evt);
            }
        });
        tblPacientes.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblPacientesInputMethodTextChanged(evt);
            }
        });
        tblPacientes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblPacientesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 560, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Pacientes"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nascimento:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 100, 14);

        txtNascimento.setColumns(8);
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setText("   ");
        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNascimento);
        txtNascimento.setBounds(120, 80, 90, 20);
        jPanel1.add(txtPaciente);
        txtPaciente.setBounds(124, 40, 420, 20);

        jLabel2.setText("Paciente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 100, 14);

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 80, 14);

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(cmbSexo);
        cmbSexo.setBounds(120, 120, 110, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 560, 170);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 200, 90, 23);

        jButton2.setText("Excluir");
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 200, 90, 23);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(60, 200, 90, 23);

        setSize(new java.awt.Dimension(628, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseReleased

    }//GEN-LAST:event_tblPacientesMouseReleased

    private void tblPacientesInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblPacientesInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPacientesInputMethodTextChanged

    private void tblPacientesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblPacientesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPacientesPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtPaciente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher nome do paciente");
        } else if (txtNascimento.getText().equals(" / / ")) {
            JOptionPane.showMessageDialog(null, "Preencher data de nascimento");
        } else {
            Paciente pac = this.montaPaciente();
            String gravar = new PacienteDAO().gravarPaciente(pac);
            if (gravar.equals("OK")) {
                carregarLista();
                JOptionPane.showMessageDialog(null, "Paciente Salvo com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao gravar paciente: " + gravar);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
