/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author logonpta
 */
public class FormCompra extends javax.swing.JFrame {

    /**
     * Creates new form FormCompra
     */
    public FormCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optEx = new javax.swing.JRadioButton();
        optElx = new javax.swing.JRadioButton();
        optHlx = new javax.swing.JRadioButton();
        botCalcular = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha janela monstro");
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Modelo"));
        jPanel1.setLayout(null);

        buttonGroup1.add(optEx);
        optEx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        optEx.setText("EX");
        jPanel1.add(optEx);
        optEx.setBounds(12, 23, 39, 23);

        buttonGroup1.add(optElx);
        optElx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        optElx.setText("ELX");
        jPanel1.add(optElx);
        optElx.setBounds(12, 46, 45, 23);

        buttonGroup1.add(optHlx);
        optHlx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        optHlx.setText("HLX");
        jPanel1.add(optHlx);
        optHlx.setBounds(12, 69, 47, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 150, 150);

        botCalcular.setText("Calcular");
        botCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botCalcular);
        botCalcular.setBounds(30, 190, 150, 40);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(40, 250, 330, 20);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCalcularActionPerformed
        float valor = 0;
        
        if(optEx.isSelected()){
            valor = 1000;
        }else if(optElx.isSelected()){
            valor = 1500;
        }else if(optHlx.isSelected()){
            valor = 2000;
        }else{
            lblMessage.setText("Seleciona um botão mané");
        }
        
        if(valor > 0 ){
            lblMessage.setText("O valor é: "+valor);
        }
    }//GEN-LAST:event_botCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JRadioButton optElx;
    private javax.swing.JRadioButton optEx;
    private javax.swing.JRadioButton optHlx;
    // End of variables declaration//GEN-END:variables
}
