/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import estatica.Pilha;

/**
 *
 * @author igor
 */
public class ManipulacaoPilha extends javax.swing.JFrame {
    Pilha p = new Pilha();
    /**
     * Creates new form ManipulacaoPilha
     */
    public ManipulacaoPilha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInserir = new javax.swing.JTextField();
        btnInserirTopo = new javax.swing.JButton();
        btnExcluirTopo = new javax.swing.JButton();
        btnMostrarTopo = new javax.swing.JButton();
        btnMostrarTudo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imanipulação de Pilha"));
        jPanel1.setLayout(null);

        jLabel1.setText("Inserir na Pilha");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 24, 120, 20);
        jPanel1.add(txtInserir);
        txtInserir.setBounds(10, 50, 70, 30);

        btnInserirTopo.setText("Inserir");
        btnInserirTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirTopoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirTopo);
        btnInserirTopo.setBounds(90, 50, 70, 23);

        btnExcluirTopo.setText("Excluir da Pilha");
        btnExcluirTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTopoActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirTopo);
        btnExcluirTopo.setBounds(10, 90, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 190, 160);

        btnMostrarTopo.setText("Mostrar topo");
        btnMostrarTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTopoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTopo);
        btnMostrarTopo.setBounds(220, 20, 130, 70);

        btnMostrarTudo.setText("Mostrar Tudo");
        btnMostrarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTudoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTudo);
        btnMostrarTudo.setBounds(220, 110, 130, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));
        jPanel2.setLayout(null);

        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblOutput);
        lblOutput.setBounds(10, 20, 300, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 180, 330, 100);

        setSize(new java.awt.Dimension(392, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTopoActionPerformed
        lblOutput.setText(p.top()+" deletado com sucesso");
        p.pop();
    }//GEN-LAST:event_btnExcluirTopoActionPerformed

    private void btnMostrarTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTopoActionPerformed
        lblOutput.setText(""+p.top());//p.top() n pode ser exibido porque é um objeto mas ""+p.top()pode porque vira uma String
    }//GEN-LAST:event_btnMostrarTopoActionPerformed

    private void btnInserirTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirTopoActionPerformed
        p.push(txtInserir.getText());
        lblOutput.setText(p.top()+" inserido com sucesso");
    }//GEN-LAST:event_btnInserirTopoActionPerformed

    private void btnMostrarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTudoActionPerformed
        lblOutput.setText(p.returnPilha());
    }//GEN-LAST:event_btnMostrarTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipulacaoPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipulacaoPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipulacaoPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipulacaoPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipulacaoPilha().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirTopo;
    private javax.swing.JButton btnInserirTopo;
    private javax.swing.JButton btnMostrarTopo;
    private javax.swing.JButton btnMostrarTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JTextField txtInserir;
    // End of variables declaration//GEN-END:variables
}
