CREATE TABLE TB_HABILITACAO
(ID_CPF VARCHAR2(11),
NM_HABILITADO VARCHAR2(50) NOT NULL,
DS_ENDERECO VARCHAR2(50) NOT NULL,
ID_CEP VARCHAR2(8) NOT NULL,
DS_BAIRRO VARCHAR2(40) NOT NULL,
F1_CATEGORIA CHAR(1) NOT NULL,
DT_VENCIMENTO DATE NOT NULL,
    CONSTRAINT TB_HABILITACAO_ID_CPF_PK PRIMARY KEY(ID_CPF)
);

CREATE TABLE TB_COMBUSTIVEL
(ID_COMBUSTIVEL NUMBER(2),
DS_COMBUSTIVEL VARCHAR2(50) NOT NULL,
TX_IPVA NUMBER(4,2) NOT NULL,
CONSTRAINT TB_COMBUSTIVEL_ID_COMBUSTIVEL_PK PRIMARY KEY(ID_COMBUSTIVEL)
);

CREATE TABLE TB_MULTA
(ID_MULTA NUMBER(6),
DS_MULTA VARCHAR(50) NOT NULL,
NR_PONTOS NUMBER(2) NOT NULL,
NR_VALOR NUMBER(12,2) NOT NULL,
 CONSTRAINT TB_MULTA_ID_MULTA_PK PRIMARY KEY(ID_MULTA)
);

CREATE TABLE TB_VEICULOS
(ID_PLACA VARCHAR2(8),
DS_RENAVAM VARCHAR2(13) NOT NULL,
DS_MARCA VARCHAR2(40) NOT NULL,
DS_MODELO VARCHAR2(40) NOT NULL,
DS_ANO_FABRIC NUMBER(4) NOT NULL,
DS_ANO_MODELO NUMBER(4) NOT NULL,
DS_COR VARCHAR2(40) NOT NULL,
ID_COMBUSTIVEL NUMBER(2) NOT NULL,
 CONSTRAINT TV_VEICULOS_ID_PLACA_PK PRIMARY KEY(ID_PLACA),
 CONSTRAINT TV_VEICULOS_ID_COMBUSTIVEL_FK FOREIGN KEY(ID_COMBUSTIVEL)
 REFERENCES TB_COMBUSTIVEL(ID_COMBUSTIVEL)
);

CREATE TABLE TB_HISTORICO
(ID_CPF VARCHAR2(11),
ID_PLACA VARCHAR2(8),
DT_AQUISICAO DATE NOT NULL,
DT_VENDA DATE,
    CONSTRAINT TB_HISTORICO_ID_CPF_ID_PLACA_PK PRIMARY KEY(ID_CPF,ID_PLACA),
    CONSTRAINT TB_HISTORICO_ID_CPF_FK FOREIGN KEY(ID_CPF)
    REFERENCES TB_HABILITACAO(ID_CPF),
    CONSTRAINT TB_HISTORICO_ID_PLACA_FK FOREIGN KEY(ID_PLACA)
    REFERENCES TB_VEICULOS(ID_PLACA)
); 

CREATE TABLE TB_INFRACAO
(ID_MULTA NUMBER(6),
ID_PLACA VARCHAR2(8),
DT_INFRACAO DATE NOT NULL,
DS_LOCAL VARCHAR2(50) NOT NULL,
FL_PAGA VARCHAR2(1) NOT NULL,
    CONSTRAINT TB_INFRACAO_ID_MULTA_ID_PLACA_PK PRIMARY KEY(ID_MULTA,ID_PLACA),
    CONSTRAINT TB_INFRACAO_ID_MULTA_FK FOREIGN KEY(ID_MULTA)
    REFERENCES TB_MULTA(ID_MULTA),
    CONSTRAINT TB_INFRACAO_ID_PLACA_FK FOREIGN KEY(ID_PLACA)
    REFERENCES TB_VEICULOS(ID_PLACA)
);