/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Candidato;
import classes.Eleitor;
import dao.CandidatoDAO;
import dao.EleitorDAO;
import javax.swing.JOptionPane;


public class CadastrarVoto extends javax.swing.JInternalFrame {

    private Eleitor  montaEleitor(){
        Eleitor eleitor = new Eleitor();
        eleitor.setTitulo(txtTitulo.getText());
        
        
        return eleitor;
    }
    public CadastrarVoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));
        jPanel1.setLayout(null);
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(60, 40, 360, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 450, 120);

        jButton1.setText("Iniciar Votação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 182, 160, 40);

        setBounds(0, 0, 497, 268);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result = new EleitorDAO().analisaEleitor(txtTitulo.getText());
        Eleitor eleitor = montaEleitor();
            

        switch (result) {
            case 1:
                JOptionPane.showMessageDialog(null, "Eleitor já voltou");
                break;
            case 2:
                Urna urna = new Urna();
                urna.setVisible(true);
                String resp = new EleitorDAO().updateEleitor(eleitor);
                
                
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Titulo não cadastrado");
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
