/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Eleitor;
import dao.EleitorDAO;
import javax.swing.JOptionPane;

public class Eleitores extends javax.swing.JInternalFrame {

    private Eleitor  montaEleitor(){
        Eleitor eleitor = new Eleitor();
        eleitor.setTitulo(txtTitulo.getText());
        eleitor.setNome(txtNome.getText());
        
        return eleitor;
    }
    public Eleitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        txtTitulo1 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Eleitor"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(51, 71, 36, 16);

        jLabel2.setText("Titulo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 34, 16);
        jPanel1.add(txtNome);
        txtNome.setBounds(110, 70, 300, 24);
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(110, 130, 300, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 450, 260);

        jToggleButton1.setText("Salvar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(350, 310, 130, 50);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Eleitor"));
        jPanel2.setLayout(null);

        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(51, 71, 36, 16);

        jLabel4.setText("Titulo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 130, 34, 16);
        jPanel2.add(txtNome1);
        txtNome1.setBounds(110, 70, 300, 24);
        jPanel2.add(txtTitulo1);
        txtTitulo1.setBounds(110, 130, 300, 24);

        jInternalFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 30, 450, 260);

        jToggleButton2.setText("Salvar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(350, 310, 130, 50);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 80, 22);

        setBounds(0, 0, 506, 426);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       String salvar = new EleitorDAO().insereEleitor(montaEleitor());
       
       if (salvar.equals("OK")) {
           JOptionPane.showMessageDialog(null, "Eleitor gravado com sucesso");
       } else {
           JOptionPane.showMessageDialog(null, salvar);
       }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
