/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author igor
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtRgm = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nota2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 140, 34, 14);

        jLabel2.setText("RGM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 22, 14);

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 34, 14);

        jLabel4.setText("Nota1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 34, 14);

        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota2);
        txtNota2.setBounds(90, 140, 80, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 80, 80, 20);

        txtRgm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgmActionPerformed(evt);
            }
        });
        getContentPane().add(txtRgm);
        txtRgm.setBounds(90, 50, 80, 20);

        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota1);
        txtNota1.setBounds(90, 110, 80, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagem"));
        jPanel1.setLayout(null);

        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMensagem);
        lblMensagem.setBounds(10, 10, 200, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 179, 220, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos"));
        jPanel2.setLayout(null);

        btnSair.setText("Sair");
        jPanel2.add(btnSair);
        btnSair.setBounds(20, 110, 100, 23);

        btnSalvar.setText("Salvar");
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(20, 20, 100, 23);

        btnPesquisar.setText("Pesquisar");
        jPanel2.add(btnPesquisar);
        btnPesquisar.setBounds(20, 50, 100, 23);

        btnCalcular.setText("Calcular");
        jPanel2.add(btnCalcular);
        btnCalcular.setBounds(20, 80, 100, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 120, 150, 160);

        setSize(new java.awt.Dimension(460, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtRgmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgmActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtRgm;
    // End of variables declaration//GEN-END:variables
}
