/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Aluno;
import dao.AlunoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amilton
 */
public class Grade extends javax.swing.JFrame {

    /**
     * Creates new form Grade
     */
    public Grade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrade = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Linha 1", "87"},
                {"Linha 2", "356"},
                {"Linha 3", "56"}
            },
            new String [] {
                "Coluna 1", "Coluna 2"
            }
        ));
        tblGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblGradeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrade);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 20, 452, 160);

        jButton1.setText("Filósofos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 200, 120, 30);

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 200, 120, 30);

        jButton3.setText("Carrega Banco");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 200, 120, 30);

        setBounds(0, 0, 620, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String titulos[] = {"Identificação", "Nome"};
        Object dados[][] = {
            {1, "Sócrates"},
            {2, "Platão"},
            {3, "Aristóteles"},
            {4, "Kant"},
            {5, "Descartes"}};
        DefaultTableModel modelo
                = new DefaultTableModel(dados, titulos);
        tblGrade.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblGrade.getModel();
        modelo.addRow(new String[]{"6", "Locke"});
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblGradeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGradeMouseReleased

        if (tblGrade.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nada selecionado");
        } else {
            int it = tblGrade.getSelectionModel().getMinSelectionIndex();
            String escolhido = tblGrade.getModel().getValueAt(it, 0) + ", "
                    + tblGrade.getModel().getValueAt(it, 1);
            JOptionPane.showMessageDialog(null, escolhido);
        }
    }//GEN-LAST:event_tblGradeMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<Aluno> lista = new AlunoDAO().listaAlunos();
        DefaultTableModel modelo = (DefaultTableModel) tblGrade.getModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{lista.get(i).getRgm(),
                lista.get(i).getNome()});
        }
    }//GEN-LAST:event_jButton3ActionPerformed
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grade.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grade.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grade.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grade.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGrade;
    // End of variables declaration//GEN-END:variables
}
