/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Funcionario;
import dao.FuncionarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author igor
 */
public class Cadastro extends javax.swing.JFrame {

    public Cadastro() {
        initComponents();
    }
    
    private Funcionario montaFuncionario(){
        Funcionario funcionario = new Funcionario();
        
        funcionario.setCpf(txtCpf.getText());
        funcionario.setNome(txtNome.getText());
        funcionario.setSalario(Float.parseFloat(txtSalario.getText()));
        
        if(optMasculino.isSelected()){
            funcionario.setSexo('M');
        } else {
            funcionario.setSexo('F');
        }
        
        return funcionario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtSalario = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        optMasculino = new javax.swing.JRadioButton();
        optFeminino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Funcionarios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 210, 40);

        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 19, 14);

        txtCpf.setText("jTextField1");
        getContentPane().add(txtCpf);
        txtCpf.setBounds(70, 60, 120, 20);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 60, 73, 23);

        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 180, 34, 14);

        jLabel4.setText("Nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 27, 14);

        jLabel5.setText("Salario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 140, 34, 14);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluir);
        btnIncluir.setBounds(30, 250, 61, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(130, 250, 65, 23);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(250, 250, 73, 23);

        txtSalario.setText("jTextField2");
        getContentPane().add(txtSalario);
        txtSalario.setBounds(100, 140, 160, 20);

        txtNome.setText("jTextField2");
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 100, 160, 20);

        Sexo.add(optMasculino);
        optMasculino.setText("Masculino");
        getContentPane().add(optMasculino);
        optMasculino.setBounds(100, 180, 71, 23);

        Sexo.add(optFeminino);
        optFeminino.setText("Feminino");
        getContentPane().add(optFeminino);
        optFeminino.setBounds(190, 180, 67, 23);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        String resp = new FuncionarioDAO().insereFuncionario(montaFuncionario());
        if (resp.equals("OK")){
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, resp);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       String resp =new FuncionarioDAO().alterarFuncionario(montaFuncionario());
       if (resp.equals("OK")){
            JOptionPane.showMessageDialog(null, "Alterado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, resp);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String resp = new FuncionarioDAO().excluirFuncionario(montaFuncionario());
        if (resp.equals("OK")){
            JOptionPane.showMessageDialog(null, "Excluido com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, resp);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Funcionario func = new FuncionarioDAO().buscaFuncionario(txtCpf.getText());
        
        if (func == null){
            JOptionPane.showMessageDialog(null, "Funcionario não encontrado");
        } else {
            txtCpf.setText(func.getCpf());
            txtNome.setText(func.getNome());
            txtSalario.setText(func.getSalario()+ "");
            if(func.getSexo() == 'M'){
                optMasculino.setSelected(true);
            } else {
                optFeminino.setSelected(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton optFeminino;
    private javax.swing.JRadioButton optMasculino;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
