DELETE FROM TB_TIPOCONTA;
DELETE FROM TB_CLIENTE;
DELETE FROM TB_CONTA;

INSERT INTO TB_TIPOCONTA
    VALUES (80, 2424, 1);
INSERT INTO TB_TIPOCONTA
    VALUES (90, 4545, 1);
INSERT INTO TB_TIPOCONTA
    VALUES (50, 5858, 0);
INSERT INTO TB_TIPOCONTA
    VALUES (44, 9998, 0);
INSERT INTO TB_TIPOCONTA
    VALUES (99, 2121, 0);
INSERT INTO TB_TIPOCONTA
    VALUES (11, 1010, 1);

INSERT INTO TB_CONTA
    VALUES (1, 'Conta 1', 50);
INSERT INTO TB_CONTA
    VALUES (2, 'Conta 2', 90);
INSERT INTO TB_CONTA
    VALUES (3, 'Conta 3', 80);
INSERT INTO TB_CONTA
    VALUES (4, 'Conta 4', 44);
INSERT INTO TB_CONTA
    VALUES (5, 'Conta 5', 99);
INSERT INTO TB_CONTA
    VALUES (6, 'Conta 6', 11);

INSERT INTO TB_CLIENTE
    VALUES (1, 'teste1', 11111111, 'F');
INSERT INTO TB_CLIENTE
    VALUES (2, 'teste2', 2222222, 'J');
INSERT INTO TB_CLIENTE
    VALUES (3, 'teste3', 3333333, 'F');
INSERT INTO TB_CLIENTE
    VALUES (4, 'teste4', 55555555, 'J');
INSERT INTO TB_CLIENTE
    VALUES (5, 'teste5', 4444444, 'J');
INSERT INTO TB_CLIENTE
    VALUES (6, 'teste6', 666666, 'F');

INSERT INTO TB_CLIENTECONTA
    VALUES (1, 1);
INSERT INTO TB_CLIENTECONTA
    VALUES (2, 1);
INSERT INTO TB_CLIENTECONTA
    VALUES (3, 4);
INSERT INTO TB_CLIENTECONTA
    VALUES (4, 3);
INSERT INTO TB_CLIENTECONTA
    VALUES (5, 5);
INSERT INTO TB_CLIENTECONTA
    VALUES (6, 6);
INSERT INTO TB_CLIENTECONTA
    VALUES (6, 1);
INSERT INTO TB_CLIENTECONTA
    VALUES (4, 2);
INSERT INTO TB_CLIENTECONTA
    VALUES (2, 3);
INSERT INTO TB_CLIENTECONTA
    VALUES (3, 2);

INSERT INTO TB_MOVIMENTACAO
    VALUES (1, 1, DATE '2015-03-04', 'Movimentacao 1');
INSERT INTO TB_MOVIMENTACAO
    VALUES (2, 1, DATE '2018-12-14', 'Movimentacao 2');
INSERT INTO TB_MOVIMENTACAO
    VALUES (3, 4, DATE '2018-12-12', 'Movimentacao 3');
INSERT INTO TB_MOVIMENTACAO
    VALUES (4, 3, DATE '2020-02-25', 'Movimentacao 4');
INSERT INTO TB_MOVIMENTACAO
    VALUES (5, 5, DATE '2019-10-31', 'Movimentacao 5');
INSERT INTO TB_MOVIMENTACAO
    VALUES (6, 6, DATE '2020-03-07', 'Movimentacao 6');
INSERT INTO TB_MOVIMENTACAO
    VALUES (6, 1, DATE '2017-09-01', 'Movimentacao 7');
INSERT INTO TB_MOVIMENTACAO
    VALUES (4, 2, DATE '2017-03-05', 'Movimentacao 8');
INSERT INTO TB_MOVIMENTACAO
    VALUES (2, 3, DATE '2018-03-10', 'Movimentacao 9');
INSERT INTO TB_MOVIMENTACAO
    VALUES (3, 2, DATE '2018-04-04', 'Movimentacao 10');

SELECT * from tb_cliente where id_tipocliente = 'J';
SELECT nm_cliente, ie_cpf_cnpj from TB_CLIENTE where nm_cliente like 'P%';

SELECT * from TB_MOVIMENTACAO where dt_movimentacao between date '2018-01-01' and date '2018-05-13';

SELECT nm_cliente from tb_cliente where id_tipocliente <> 'J';

update tb_tipoconta
    set ie_ativo = 1 where ie_ativo = 0;
    
delete from tb_movimentacao
    where cd_conta = 2 and cd_cliente = 3 and dt_movimentacao > date '2018-02-02';
