/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estatica.view;

import estatica.aplicacoes.Npr;

/**
 *
 * @author logonpta
 */
public class FormNPR2 extends javax.swing.JFrame {

    /**
     * Creates new form FormNPR
     */
    public FormNPR2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtInfixa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNPR = new javax.swing.JTextField();
        btnConverter = new javax.swing.JButton();
        txtResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Notação Infixa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 90, 30);

        txtInfixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfixaActionPerformed(evt);
            }
        });
        getContentPane().add(txtInfixa);
        txtInfixa.setBounds(30, 60, 140, 30);

        jLabel2.setText("Notação Polonesa Reversa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 150, 30);

        txtNPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPRActionPerformed(evt);
            }
        });
        getContentPane().add(txtNPR);
        txtNPR.setBounds(30, 160, 170, 30);

        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });
        getContentPane().add(btnConverter);
        btnConverter.setBounds(30, 100, 100, 23);

        txtResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtResult);
        txtResult.setBounds(240, 110, 100, 90);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 60, 73, 23);

        setSize(new java.awt.Dimension(402, 292));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInfixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfixaActionPerformed

    private void txtNPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPRActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        String npr = Npr.toNPR2(txtInfixa.getText());
        
        txtNPR.setText(npr);
    }//GEN-LAST:event_btnConverterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float npr;
        npr = Npr.solveNPR(txtNPR.getText());
        
        txtResult.setText(npr+"");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNPR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtInfixa;
    private javax.swing.JTextField txtNPR;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
